name: Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy infrastructure environment
    runs-on: ${{ matrix.os }}
    environment: ${{ matrix.env }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        env: [dev, pre, pro]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      #- name: 'Az CLI login'
      #  uses: azure/login@v1
      #  with:
      #    tenant-id: ${{ secrets.TENANT_ID }}
      #    subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      #    allow-no-subscriptions: true
      
      - name: Deploy ${{ matrix.env }} environment
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/src/deploy.sh"
          ${GITHUB_WORKSPACE}/src/deploy.sh \
            -r ${{ secrets.RESOURCE_GROUP }} \
            -s ${{ secrets.STORAGE_ACCOUNT }} \
            -c ${{ secrets.CONTAINER_NAME }} \
            -k ${{ secrets.TF_STATE_KEY }} \
            -l ${{ secrets.LOCATION }} \
            -e ${{ matrix.env }}