name: Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy dev infrastructure environment
    runs-on: ubuntu-20.04
    environment: dev
    steps:
      - uses: actions/checkout@v2
      
      - shell: bash
        name: Deploy Azure infrastructure
        run: |
          chmod +x "${GITHUB_WORKSPACE}/src/deploy.sh"
          ${GITHUB_WORKSPACE}/src/deploy.sh \
            -r ${{ secrets.resource_group }} \
            -s ${{ secrets.storage_account }} \
            -c ${{ secrets.container_name }} \
            -k ${{ secrets.tf_state_key }} \
            -l ${{ secrets.location }} \
            -e dev \
            -t ${{ secrets.tenant_id }} \
            -u ${{ secrets.subscription_id }}
