name: Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy dev infrastructure environment
    runs-on: ubuntu-20.04
    environment: dev
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
      
      - shell: bash
        name: Deploy Azure infrastructure
        run: |
          chmod +x "${GITHUB_WORKSPACE}/src/deploy.sh"
          ${GITHUB_WORKSPACE}/src/deploy.sh \
            -r ${{ secrets.RESOURCE_GROUP }} \
            -s ${{ secrets.STORAGE_ACCOUNT }} \
            -c ${{ secrets.CONTAINER_NAME }} \
            -k ${{ secrets.TF_STATE_KEY }} \
            -l ${{ secrets.LOCATION }} \
            -e dev
